### ISSUE TITLE
including --text uses the name of the file.

### ISSUE THREAD

**Issue by jtoy** [souzatharsis/podcastfy#198]
I am generating podcasts from the command like like so:

python -m podcastfy.client --text news.txt --topic "my topic -cc lib/podcasts/config.yml  --longform

Every podcast I generates mentions news.txt. Why would it use the file name as part of the content? Can I get rid of this?
This looks like some kind of bug.

**Comment by souzatharsis** [comment]
It's because --text receives a string (raw input text), not a text file
path.

We are yet to enable text file as input (believe or not) even though we can
process pdf, website, images etc.

Best Regards,

--
Thársis
souzatharsis.com <http://www.souzatharsis.com/>
<http://linkedin.com/in/tharsissouza>

**Comment by jtoy** [comment]
haha, thats funny.  I was reading through the source code and was confused as to why I couldn't find the text input, now it makes sense. I saw the PR to add support for it as well.

**Comment by jtoy** [comment]
it would make sense that a file would be the first thing to be fully supported?

**Comment by souzatharsis** [comment]
Yes, I agree 😅
