### ISSUE TITLE
Problem using --transcript with PDF files

### ISSUE THREAD

**Issue by ljDK-GH** [souzatharsis/podcastfy#24]
Whenever I try using --transcript switch with a PDF file, I keep getting the following error. Different PDF files give the same error.

```
(podcastify) H:\podcastify>python -m podcastfy.client --transcript "E:\Download\Wolfram S. What Is ChatGPT Doing ... and Why Does It Work 2023.pdf"
2024-10-07 23:45:46,500 - __main__ - INFO - Using transcript file: E:\Download\Wolfram S. What Is ChatGPT Doing ... and Why Does It Work 2023.pdf
2024-10-07 23:45:46,540 - __main__ - ERROR - An error occurred in the process_links function: 'charmap' codec can't decode byte 0x81 in position 785: character maps to <undefined>
An error occurred: 'charmap' codec can't decode byte 0x81 in position 785: character maps to <undefined>
```

One of the PDF file that I've tried using :
[Wolfram S. What Is ChatGPT Doing ... and Why Does It Work 2023.pdf](https://github.com/user-attachments/files/17281342/Wolfram.S.What.Is.ChatGPT.Doing.and.Why.Does.It.Work.2023.pdf)

**Comment by 240db** [comment]
you might have to edit https://github.com/souzatharsis/podcastfy/blob/main/podcastfy/content_parser/pdf_extractor.py in your local or cloud instance to handle the unicode 0x81 . 

You need to edit the line where you have normalized_content : 
```python

                # Normalize the text to handle special characters and remove accents
                normalized_content = unicodedata.normalize('NFKD', content).encode('ascii', 'ignore').decode('utf-8')
```
I still have to test it myself, but i will be following this because parsing pdfs and markdowns will be the main use for me.

**Comment by souzatharsis** [comment]
Hi @240db @ljDK-GH , in order to process an input pdf please follow this syntax, where PATH_TO_PDF_FILE contains the full path to your pdf file:

python -m podcastfy.client --url PATH_TO_PDF_FILE

You are observing the above error because you are using the syntax to generate audio from a transcript for which you are providing a pdf file. 

python -m podcastfy.client --transcript PATH_TO_TRANSCRIPT_FILE

The above will actually take the txt file from PATH_TO_TRANSCRIPT_FILE and generate a corresponding audio.
