### ISSUE TITLE
Question About Alternate to Gemini

### ISSUE THREAD

**Issue by vectrocomputers** [souzatharsis/podcastfy#36]
Not really an issue, but a question. Is it possible to swap out Gemini with a local LLM?

**Comment by souzatharsis** [comment]
Thanks for the question. Short answer is: No.

However, I am about to push an update that refactor the code to use lang-chain therefore paving the way to enable your request, ability to run local LLMs.

Note that Gemini was particularly chose as default model due to its ultra-large context window which allows for RAG-style LLM prompting out of the box.

Once I push the langchain update, I have plans to enable ease of switch among any LLMs.

I hope that answers your question. And I'd encourage you to consider becoming a contributor.

Thanks!
